apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca-bundle
  namespace: headlamp
spec:
  secretName: cluster-ca-bundle
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: "headlamp-ca-bundle"
  duration: 87600h
