---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: mongo-secret
  namespace: authent-app
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /authent-app/mongo-secret
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: mongo-secret
      namespace: authent-app
      creationPolicy: Owner
      secretType: Opaque
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: authent-app-secrets
  namespace: authent-app
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /authent-app/authent-app-secrets
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: authent-app-secrets
      namespace: authent-app
      creationPolicy: Owner
      secretType: Opaque
