apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: authent-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBfB++T462u53JuJoE7g2f33CgRQ2TCgxvwzSYeqmtGSSXFXujD4C7mtkLYI6YKvhnF2sUS6QEdl4T8AE0nJXcz4N/IIIWHvzAFxcaMBC1uydDJESRMfS4YpOkCagc9o7ZejqkZgexUbVXs/VqPqoRa9iI0tztgnUhHdHOOKCkI4UW3Fc3ymKmMAdoy8DQo17FE++RwFLlqavv+blVJ/dmqk9oLvyYemwsJUMXEJC7HaQnGdYlWIuABsoSrlsps7RKm53qxMUFxOT8w+mNjFUIc7qj9xPcOU+NAI/x6cSf7innuA8RQ8y01lNsM9IMMxHifnaczkK0m3LhDyfCid2j2IZodlMnfgnIRMCc/tYyGs6/DWVkTwa2Wqsa5ENEkRofkkMkI/KgWZ+V5IsMSAdtHCJoig8xBkhpjKtDLHM4HKjyFPp+RSKZOrJ6CoMIR13+mPl8ED6Nc+0lYxwPB7AlWZAC3wz09RO/cbcLEN7Z6xUD0+Xp1UsityU5Jvz3FdHMn2HJFv5koorv96CdFj0odhdgYFTbov9g7iTGwTuV4dDQki7nUd+iFfEL4FymSZzUw1iD6qquwgUw7DoVbvo2vECJdmypRurgcr6x/+ozO48DIzVPMBWSsL7Mwbe5xMv7sza37OGEdYT+HXxfoZTR8Bry/PPLMH6gShYb6lQVS/AGuZMqP+aGp6DN5iIV47yalSF4k2oPm09TvC/RUqq4aO90=
    MONGO_INITDB_ROOT_USERNAME: AgAkZ9ngA7MpJmm2BmtkTbUPjPvw/BNCXFsfRmQR9YktVAxxnY7+5k3XjGtJ7XftEWWP0cYqedwaO9NQucfmnEdmjt7DeYw/sYQ0hcMnxjY7HVEU2svgy8xyiSeGlUyRbKRHdxPClSFGmOcevGJTwR9zfIoOTfZHji6++RkH10lrBshhzebXSDkbcXazDlS2VJQEVJmM9mfYO5WIdKRNQbETNRWOcjm3KERETX1nrvkACa/dRzqGxacu6cror4Vrn458zIkYWsejKjFRz6tkPLB15A3/v8Svh6F5WKr+WjknLcF1d3dlltUmOaoLQCEjcTJoM5Ess1U5x59LoXKAG1fg6VqCVm/2uuBzx5zaiVHezWYTIAz4tBAd5Bg2Jd43WJTPe05sfpbYUC43ND+MrcXEi+JDoVlc8xVkc18p8g/spxArOhbXJaR3JtwnRZCF1wSOu89um2HJQ9APJxFxCsuWzDX1LAdT8JXg7EwK0vLGOfwC7mqixOKvB3CsPhkW2p+idAKgQj0IShNsZ1xapqQeTRAwx7bkZAIy0fL0ZpXon3RreEHfFeBQ6SewQZpsqQCfyTdv7jmIfQL9QFA0hxf4pKcMW0PFP705LA9QmIWec5eDBrWxTUFDirvxrD9UdJCFHkAKPCq465pvqz4jGmlqIUHXMVdM2mITiQ2dVWbAyfWjX8XVxKx+00FiwRRTSAk3aWM9/Q==
  template:
    metadata:
      name: mongo-secret
      namespace: authent-app
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authent-app-secrets
  namespace: authent-app
spec:
  encryptedData:
    JWT_SECRET: AgBjX6JxhCsKPW8WsYki8aL4r4Arx7dJ6tyqgS/FdLIj6kLIRbTzQeCEyK661+m8wCgkiYMXM+vZDnYTTxjao7K7Oywt+s8PiESAuLTEe+a45+8COU27ajI3XSwUSQWUcD/sWYyVP1nv3jPbnzys4pq2nYUPOJFeIk5kpdKy8bRNh6BYUWs/Um2NOk3hh3cGZGi2mk4aqki0ctPJlMqGD07dMk5WBRadvf6QBIZQj+2cxmD19yeDdsuDv7lrTDpi9o6fIgenYvqNF8oOccW/JMmDNtyBXQCzYXHmLc5R1xTYsS8MTVuzp1vZRyt5GlifnhjIx9efsaNc7w0X63OmZ+iqAC4/cpdA+Xtaxa06sOVG2zj91vcG0iFpNekh5JQlitzYEPLP7HWZDZ6SAD9oOGcPhCFiqpCPIpaUYN/YJpAKNLGUIHEoeIXWzEIjxkT1+hJ8X3BS3D27aM10lsWhm1kbWWyLOByGBst4Xu18WB4lFBrWTOzLtUBXWSsM+DSgsO9DDRl7MU3a5gtp09JzVulbBfmZJmtPlHKRG0KgCD+YcnzM9+SFMRy1AwRB2DDXFyxJ65GzAKuJjhKW4poDSl+w/iE+srWzvPi3FfZPU5mw2QZ5qRJ2Z4SSOZDV7qIA37J85w6kpk9abNTvzXmSnOphmum2saTmjOwzDfDaePA6ryrLB1azMjuX5rMem+33uqAZMF7yJeSJwJNQe8u4ZTVwS558UogWEH9bnXVIgQ==
  template:
    metadata:
      name: authent-app-secrets
      namespace: authent-app
