---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCerHewVxQR37WqRhwG/cnPMp9OJnyIYFI+qxgdecrek2y1RXIRIz3pLQw1DchcHZ2zcl99C9Kqxb1TRws/nOT+DkYm/6yJ4DufWuKPRu4JVv7lS7gShKej7BsSxW4Rh+5GYeOxYRexpp9wYzxLAP0M2zstxSHxNDMMFAQWzXzKwphClRQGgF0n31lx3OKD1Eok1YR40Wxi9bQ4F6lYthKyCw4s1EVmu5napqr9r8yz0UE5b2W2UaIyTP9idNjOoL/czear1qnN1pbCwdLY/6yqH8Ut7jChAWMJA841KAkf4NW6KlQRTMvrFiTKIb1r2b/XFoA4AqelabCLbJJltFdWtbO3VZ8Q2GFC+dymY8ia24EV1XHQUeYw4+eXQ9YtbE9nfbtllTvzncBZs4aP3y2jT4ejYR7PATZ83cCS5AQ3ZJajaFSxDRseEAqEc8w3mrKwqlg4n4J2i6tSI22oIBOnF8TxBW6SM6ZmrfTaI/IsKBrHNsucjEFrW9noLnIb15jNgP5eG6aZCZEbqU2ib9moMq/FsfFXBMnqk5BWRXADZ+zwoc8+Qu4Ixr8t9FvadZMzYQUSUonUqLfmjBez67R0quGCVj6yiwF5ab4xzllLsZcFpEC/lfFqFk8jc2l3bSMh5V2B3lyHpDo2Htl1U5uo+yKfDzndDKnSyirsUBi5cgRegnJFOd54f8u2DiMDmEKAyt+hjJ7OMsrQqT4=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor
