apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgB36yjVNV2GSICahKTUMV1rnTvqZY8HxKymOEsyjW014pE4iBp1336Odec7/O8Hs2sqxA1raZlOvChCzPQJlGA1YsoI+u2Qz9JijYNMvcf9K5lWWhU1YcEZjSRXZFnDs9JItdzzdPWg84d/kLuz9SaVDhedk6T8SfXfnmI8I4PCtC9RxF371YWwoKcl91deCQEw5iM87QmxW5cxznGGw+ooTn5jQBwuDRME8zHzTip5h7rijdnJzz9XNDF2EelNamNZo90TNNycZcL5S7dawoiUoWd38LZfDAjLO02PL93ce7it+E+w5SZw0roiEROx9yjEKYUcn8OYs5Jvq3BvMvQx3bS66GwUqDwtnPTY/bau4cgdkAzINxCgpxs8jMoEq/KEEvhj+ebxdLszsdmE+/dIEmW3tzUBWsa5/E3NM9y1NzL/eXGa1Guz+UkfI9dutJCVh/tcuh1Xtqy5zh13jG59D62L7N7emBpST/xWaiNOyM5WkQAZROuKKGjaJ13fws5x20GESwDixi2JzhYDvZmcbHxv7CIG4Sc4mxR3L5soAe/IxRltL/CdyeDzdtdPWNDZdgJa+5MOVCksjl97x/YjG2c+NToOaQ8EUWPWLEWXZjOnYyVYs6kgnmSU7rqCkd1jC4LRwUnJx4bbPeHpDfluIcDmLGVyForHqfBwA93+epr7sobvwsvBwyGTkJAJ2JdzvjIs18ShbA9/Q78=
  template:
    metadata:
      name: harbor-admin-secret
      namespace: harbor
