expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.cluster.local
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: ca-issuer
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls

externalURL: https://harbor.thysmadev.fr

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      size: 10Gi
    database:
      size: 2Gi
    redis:
      size: 1Gi

harborAdminPassword: "ChangeMe123!"

database:
  type: internal

redis:
  type: internal

trivy:
  enabled: true    # scanner de vulnérabilités intégré

core:
  extraEnvVars:
    - name: CONFIG_OVERWRITE_JSON
      value: >-
        {"auth_mode":"oidc_auth",
        "oidc_name":"Dex",
        "oidc_endpoint":"https://dex.thysmadev.fr",
        "oidc_client_id":"harbor",
        "oidc_client_secret":"harbor-dex-secret-change-me",
        "oidc_groups_claim":"groups",
        "oidc_scope":"openid,profile,email",
        "oidc_auto_onboard":true,
        "oidc_user_claim":"email"}