apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: ghcr-pull-secret
  namespace: onward
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /onward/ghcr-pull-secret
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: ghcr-pull-secret
      namespace: onward
      creationPolicy: Owner
      secretType: kubernetes.io/dockerconfigjson
      template:
        engineVersion: v1
        data:
          .dockerconfigjson: "{{ .dockerconfigjson.Value }}"
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: onward-secrets
  namespace: onward
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /onward/onward-secrets
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: onward-secrets
      namespace: onward
      creationPolicy: Owner
      secretType: Opaque
