apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-authent-app
  namespace: tekton-ci
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
      default: "https://github.com/ThysmaJS/AuthentApp_K3S.git"
    - name: image-reference
      type: string
      default: "thysma/authent-app:1.0.0"
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
          
    - name: build-image
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: DOCKERFILE
          value: "./Dockerfile"
      # On définit la tâche directement ici pour forcer l'auth Docker
      taskSpec:
        params:
          - name: IMAGE
          - name: DOCKERFILE
        workspaces:
          - name: source
        results:
          - name: IMAGE_DIGEST
        steps:
          - name: build-and-push
            image: gcr.io/kaniko-project/executor:latest
            env:
              - name: DOCKER_CONFIG
                value: /tekton/creds-/.docker
            command:
              - /kaniko/executor
            args:
              - --dockerfile=$(params.DOCKERFILE)
              - --context=$(workspaces.source.path)
              - --destination=$(params.IMAGE)
              - --digest-file=$(results.IMAGE_DIGEST.path)