apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-builder
  namespace: tekton-ci
secrets: # <--- Kaniko cherche ICI pour pousser l'image
  - name: dockerhub-secret
  - name: github-secret
imagePullSecrets: # <--- Kubernetes cherche ICI pour télécharger des images privées
  - name: dockerhub-secret