apiVersion: apps/v1
kind: Deployment
metadata:
  name: giiveaway-api
  namespace: giiveaway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giiveaway-api
  template:
    metadata:
      labels:
        app: giiveaway-api
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
      - name: api
        image: harbor.thysmadev.fr/giiveaway/api:656f18e07c33b3f310544e9724c54ca0b6fe8e8c
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: giiveaway-secrets
              key: database-url
        - name: JWT_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: giiveaway-secrets
              key: jwt-access-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: giiveaway-secrets
              key: jwt-refresh-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giiveaway-front
  namespace: giiveaway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giiveaway-front
  template:
    metadata:
      labels:
        app: giiveaway-front
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
      - name: front
        image: harbor.thysmadev.fr/giiveaway/front:656f18e07c33b3f310544e9724c54ca0b6fe8e8c
        ports:
        - containerPort: 80