---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: harbor-pull-secret
  namespace: giiveaway
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /giiveaway/harbor-pull-secret
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: harbor-pull-secret
      namespace: giiveaway
      creationPolicy: Owner
      secretType: kubernetes.io/dockerconfigjson
      template:
        engineVersion: v1
        data:
          .dockerconfigjson: "{{ .dockerconfigjson.Value }}"
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: giiveaway-secrets
  namespace: giiveaway
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /giiveaway/giiveaway-secrets
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: giiveaway-secrets
      namespace: giiveaway
      creationPolicy: Owner
      secretType: Opaque
