apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull-secret
  namespace: giiveaway
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"harbor.thysmadev.fr":{"username":"robot$ci-pusher","password":"sJWIYl8gcO0An4cgIV7conwGGzoyCTsj","auth":"cm9ib3QkY2ktcHVzaGVyOnNKV0lZbDhnY08wQW40Y2dJVjdjb253R0d6b3lDVHNq"}}}'
---
apiVersion: v1
kind: Secret
metadata:
  name: giiveaway-secrets
  namespace: giiveaway
type: Opaque
stringData:
  postgres-user: "giiveaway"
  postgres-password: "ChangeMe123!"
  database-url: "postgresql://giiveaway:ChangeMe123!@postgres:5432/giveaway?schema=public"
  jwt-access-secret: "8970c227f866192fefefc798dca1b7e3f0a538ffbbcf1b1661830df4c1e736f80eec7e986d52b1a6a8f8814f2d212a9586826ac1bda64cf3c71c6d791ab54a18"
  jwt-refresh-secret: "1cc367c74139cfa0920a8053412f0e0eb7be5de2a6d1cc095bc8a88e5383ef108dd21fcdc4692c8bfaafe41af301ca3ec167b38e2f00017e19344f22e4818d4a"
  brevo-api-key: "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"
  cloudinary-cloud-name: ""
  cloudinary-api-key: ""
  cloudinary-api-secret: ""
  google-client-web-id: ""
  google-android-client-id: ""
  google-ios-client-id: ""