apiVersion: batch/v1
kind: Job
metadata:
  name: giiveaway-seed
  namespace: giiveaway
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
      - name: seed
        image: harbor.thysmadev.fr/giiveaway/api:e2fbe84ac2eb53d6208b4f7a57aa51880a6e747d
        command: ["node", "dist/prisma/seed.js"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: giiveaway-secrets
              key: database-url
