apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cloudflare-ddns-token
  namespace: cloudflare-ddns
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /cloudflare-ddns/cloudflare-ddns-token
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: cloudflare-ddns-token
      namespace: cloudflare-ddns
      creationPolicy: Owner
      secretType: Opaque
