apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns-token
  namespace: cloudflare-ddns
spec:
  encryptedData:
    API_KEY: AgAQA6eC6LeECaYhRhV/kXMEYSeichnUEwqESpykAAAjXSuNf65GXqCYPt2tmccfosumtLLQU6YZpD0imILNE0bhao1z1SFRREBzWCNcvOIKfxQ1pwZut0dWeiEsVUJUrtwNTmp/I8dVMNiVeUFb96gCgjl1HpqcXTRsVqFtsWYc5sXwt4VFSEv38rU6eCDGNQ+mYbLI4QH5B4GDrluKB6vejgbvf5qyqFOBHR8lrP63taAZSXUXx9d5snV+XDlVBLewxdRBtiBM4TpJRqN8QE3i8A02cWH65W/QlGx4iGASz2t6InoytHUZzsQg+aa+Yr+pOuqwNyat6wzYoMnEHgfom1f3nuCMdkxQ7Ae4Av2XdnNSz/ixT+tn8Zp/2KwojvlbLF2+HLu0FwCp88Fs0lIJxef3/+9O8cPKMXN1BxA4Ym5IeTVnBkIi4dLbv5pHrmCGc0CfIHxhv6Q9xeQBTkDKFKbDh3GXRxYI/Dbdj7lifAOLcJ9DAxdSWdUs5rBCyCjerclW0hOKq9tE5Wzwh1fzjoPjRcSuczi32T1IJeCYWwFb87S3Hb0Q8u4IQJeh5z/uJY1XHuyiBN/XHPJZgwd30nUDWKFgssCKEx9j3vXyAAU4PCgyp3A7AvqxKW3PTpbdCWGWQBPhZdTVRNifny1DDfif2SzJteS4/WFVI3URDqhjIDKYztM+9WVljCpbuaYuOxRqBqi64uWyal7tkegUWL3VoBCiyvtglrSkKi5SRMcNUUeXhKBR3Hq5gOgDZjSyyP1D7g==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns-token
      namespace: cloudflare-ddns
