apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.0
    helm:
      valueFiles:
        - $values/infra/harbor/values.yaml
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.14.0
      helm:
        valueFiles:
          - $values/infra/harbor/values.yaml
    - repoURL: https://github.com/ThysmaJS/k3s-gitops-lab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: harbor-core
      namespace: harbor
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-jobservice
      namespace: harbor
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-registry
      namespace: harbor
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-registry-htpasswd
      namespace: harbor
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true