apiVersion: v1
kind: Service
metadata:
  name: freeroom
  namespace: freeroom
  labels:
    app: freeroom
spec:
  selector:
    app: freeroom
  ports:
    - port: 80
      targetPort: 3000
      name: http
    - port: 9464
      targetPort: 9464
      name: metrics
