apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /cloudflared/cloudflared-token
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: cloudflared-token
      namespace: cloudflared
      creationPolicy: Owner
      secretType: Opaque
