---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCE2Te5Z9hfPF+m8DLq4AC9Q5JuZAeAgL0Js4W3OiBsrvbouUsW5lrNnRK3Gwgl8+cXiPk1UqVZ4y7u/qxfttaUIvHtku6oKiM7R9epe+xoeRzwxJqvNuU8ATbxEccNdofjg/r52PLPMyvFSUdR95pvZExuL30Xgsj905gybHGuFstQJXSiQ+O1DsBGR7ax8VBYMPj5XddvWb+chOpLxxQgtpmpzKaineULmaiioX77vDIYIW85TAIprLalUxtBIo1BuU6RrSJboIKwFGFWg7QSwZfe7EvQxlrbErjafLWPGc1l2sf4NWeo5d0ovDXUk5a97l5/S32IkFJ4kw7zaG+ZyBsAamD0bQcSGH3o9gok/tQJK1faNaRwKOJ2roYX1jyGG0wrhQw/yj0h+bUQSbZuKNUO1Zn2Jq/ifxcHTEA2L36EeCMhHI/FabTFhaKftC/jYY05DNasR03Hvo44+ednzKL4EuwqUwrnw1N74h+Jq18v1LmKQgbKCFzEBA5PIqddWW3/ep5Ls+xy3CzV6rqk/Avaj98pVw6Ffo8XNE3qj5oxh2mov2hlTzFlbHt/wk/RveJ8wuLNhE3S45nitdOe+6LYWLo8URW6kU393CXxQJVtUT3mEGDcm0TRyReJxnNRDE/t+d3xb2MZtDEGhgkKnVb3oSt0hrDgIjBJiexB9/iwYT4y4Hawq+5AWs+VHOFMyTFvQqfOVpMIIaQMTkevntQ2icPH01qMcnJXsko+qSp24rL17vDL+tS4Ft55vHrhPR+/jWzjamkW7ghEpou1P5+rJ5C6OCdOv91rjssYKolw1bOAbN9mz1OwZIbl48hVx0b3jS+Ov057ZTR00NFHagMnqeWFxEWMK04nZIDOAjk8h0eo3BOqwZfrycmc1oBrYGLyvKrom1iLvGssG/AAS40Vf6cuELlurME0bQdEtTR727NEb/KD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
