apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgA5/1wKDRZPZgRkwn6HMzxTwKtPvZ62CvATJP3GNsj+9MzY5xaywxHALcrTnL1KOoTAtVKy0pAk7X6jTJWpdwHhjNBElXJjEQq8spPhX6gogkw/29jnlN23PLMkTFPGGDikMDTNfu/YOcA4410ldzdwT0hDFhkt0mI6tWGYxrp0y5PnkeNJraBKnYtTfAZgMKuYZVdjang2Baj9R9pKRaVlRzmJ43gNY7ZW6grLdDyvC1ObncJFoReinPOWWrMB8nM9qjSpEFxf3bG6ggUw2Wrwc3Y/BqGIzpx7MB03rorSVFUj18lpYKxnTLqDn2qyfV5a6Xnw8tG+7Kp0swf7XyHxA9VpQb8ZMzTlnE414ON4YwZWZLLglWRHlqpSabRphgS6kJXsq8MohbldNGqcrNrAPEBmFmKxD1ur4DNXA+3ZnEsIdtf91ft++LayouW+Z+nZNn30ihjw7eorY67xSkJzAY5lhSr2+9xJKgcFu7ZviP2iHaEUy+h+dba7G+2QkzdnieUmn7pbvq/MS5BTURRXw9zBVsd/+pBvz1JpEbbrAQNCDAjvSyYCG8Ds6G2TBiMcjRJtP9eCFv/1JkqiRy2s9HOVWWGKFP5o80BZAu6n3VTkM76nfkIkzD++TZn0bpZNOTth9oZ/HuO0Xf3uC+pWQoZekPw5qPYN/yE952bgmcXHL6gcZ+RnZ8GRFl0NAeZBWVBnrO7OjZy5cfquAMBXmbl1PjzceuVaMT5H3f45M+RlnnWdVJiP4dEf6OGV+u+kGQh2/hX78HtU9+blrqfbcFPx/fSJ15klBDK9nh5nVvNyTO9wFxbDWDqWEHWYunOYMzF6P3Gof8/7H7UXtpczEo9t7IsPMnserJHVUN0gPp6vzFMgHnp9f4cMhCmfEWA1GpdtLRmBvpykuZ5eg0VpV9gUn32xrdSsEf57V1SS799JR2iucGE
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
