apiVersion: apps/v1
kind: Deployment
metadata:
  name: michelin-backend
  namespace: michelin
  annotations:
    deploy-sha: "96eb7b6 (2026-06-16T20:15:03Z)"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: michelin-backend
  template:
    metadata:
      labels:
        app: michelin-backend
    spec:
      initContainers:
      - name: migrate
        image: ghcr.io/thysmajs/michelin-backend:latest
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DATABASE_URL
      containers:
      - name: backend
        image: ghcr.io/thysmajs/michelin-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: FRONTEND_ORIGIN
          value: "https://michelin.thysmadev.fr"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
