apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: michelin-secrets
  namespace: michelin
spec:
  infisicalAuthRef:
    name: machine-identity
    namespace: infisical
  sources:
    - projectSlug: k3s-gitops-lab
      environmentSlug: prod
      secretPath: /michelin/michelin-secrets
  syncOptions:
    refreshInterval: 5m
  targets:
    - kind: Secret
      name: michelin-secrets
      namespace: michelin
      creationPolicy: Owner
      secretType: Opaque
